# -*- coding: utf-8 -*-
"""YBI Internship Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1L6Cxt1YsokePhyYvwt20FCc4PY1X5Lz8

**Movie Recommendation System**

**Objective**

The objective of a movie recommendation system is to provide personalized and relevant movie suggestions to users based on their preferences and interests. The system aims to enhance the user's movie-watching experience by offering recommendations that align with their individual taste and increase the likelihood of finding movies they will enjoy.

The main goals of a movie recommendation system typically include:

Personalization: Tailoring recommendations to individual users based on their past movie preferences, ratings, viewing history, and demographic information. The system aims to understand the unique tastes and interests of users to provide relevant suggestions.

Discoverability: Helping users discover movies they may not have been aware of or considered before. The recommendation system can introduce users to new genres, directors, actors, or lesser-known movies that align with their interests.

User Engagement: Increasing user engagement and satisfaction by offering a seamless and enjoyable movie-watching experience. When users find recommendations that resonate with their preferences, they are more likely to spend time exploring the suggested movies and remain engaged with the platform.

Diversity and Serendipity: Balancing personalized recommendations with the inclusion of diverse and unexpected movie suggestions. While it is important to cater to individual preferences, the system should also introduce users to movies outside their comfort zone, encouraging exploration and serendipitous discoveries.

Accuracy and Relevance: Providing accurate and relevant recommendations that match the user's current context, such as mood, time of day, or occasion. The system should consider various factors to ensure the recommendations are appropriate and aligned with the user's needs at a given time.

Ultimately, the objective of a movie recommendation system is to create a personalized and enjoyable movie discovery process for users, enhancing their movie-watching experience and increasing user satisfaction and engagement.

**Import Library**
"""

importimport pandas as pd

import numpy as np

"""**Import DataSet**"""

df = pd.read_csv(r'https://raw.githubusercontent.com/YBI-Foundation/Dataset/main/Movies%20Recommendation.csv')

df.head()

df.info()

df.shape

df.columns

df_features = df[['Movie_Genre','Movie_Keywords','Movie_Tagline','Movie_Cast','Movie_Director']].fillna('')

df_features.shape

df_features

x = df_features['Movie_Genre'] + ' ' + df_features['Movie_Keywords'] + ' ' + df_features['Movie_Tagline'] + ' ' + df_features['Movie_Cast'] + ' ' + df_features['Movie_Director']

x

x.shape

from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()

x = tfidf.fit_transform(x)

x.shape

print(x)

from sklearn.metrics.pairwise import cosine_similarity

Similarity_Score = cosine_similarity(x)

Similarity_Score

Similarity_Score.shape

Favourite_Movie_Name = input(' Enter your favourite movie name: ')

All_Movies_Title_List = df['Movie_Title'].tolist()

import difflib

Movie_Recommendation = difflib.get_close_matches(Favourite_Movie_Name, All_Movies_Title_List)

Close_Match = Movie_Recommendation[0]
print(Close_Match)

Index_of_Close_Match_Movie = df[df.Movie_Title == Close_Match]['Movie_ID'].values[0]
print(Index_of_Close_Match_Movie)

Recommendation_Score = list(enumerate(Similarity_Score[Index_of_Close_Match_Movie]))
print(Recommendation_Score)

len(Recommendation_Score)

Sorted_Similar_Movies = sorted(Recommendation_Score, key = lambda x:x[1], reverse = True)
print(Sorted_Similar_Movies)

"""**Prediction:**"""

print('Top 15 Movies suggested for You : \n')
i = 1
for movie in Sorted_Similar_Movies:
  index =movie[0]
  title_from_index = df[df.index==index]['Movie_Title'].values[0]
  if (i<16):
    print(i, ',' ,title_from_index)
    i+=1